apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: default
  labels:
    app: devops-app
spec:
  type: LoadBalancer
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
